apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: default # Optional, depends on your Argo CD setup
  sources:
    - repoURL: "https://fluent.github.io/helm-charts" # public repo
      chart: fluentbit
      targetRevision: 0.48.10
      helm:
        valueFiles:
          - $values/values/fluentbit/values.yaml
    - repoURL: "https://github.com/jjgrinwis/argo-apps"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability # Namespace where Fluent Bit will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
