apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: observability # Optional, depends on your Argo CD setup
  source:
    repoURL: https://github.com/jjgrinwis/argo-apps # Your GitOps repo URL
    targetRevision: main # The branch you want to track (main, dev, release-x)
    path: apps/fluentbit # Path to your Argo CD application manifest
    helm:
      repository: https://fluent.github.io/helm-charts
      chart: fluentbit
      version: 0.48.10 # You can specify the version here or leave it out for the latest
      valueFiles:
        - ../../values/fluentbit/helm-values.yaml # Path to your custom values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability # Namespace where Fluent Bit will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
