apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  project: observability # Make sure this matches your Argo Project
  source:
    repoURL: https://github.com/your-org/your-gitops-repo.git
    targetRevision: main
    path: workloads/fluentbit
    helm:
      valueFiles:
        - helm-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
